### ISSUE TITLE
path to lint as argument

### ISSUE THREAD

**Issue by madaxel** [Liquipedia/SqlLint#2]
Hi @FO-nTTaX ,

just came along searching for sqllint with junit report type. Since your project seems to be in an early stage, maybe you can find some inspiration in https://github.com/cweiske/php-sqllint . 

We would like to switch over to the junit format. But the linting in our case is done outside of the project.

Build/tools/vendor/bin/sqllint should lint packages**/*.sql

So we need at least a parameter to specify the files/directories to lint.

Maybe these projects can be joint somehow.

**Comment by FO-nTTaX** [comment]
Hi @madaxel ,

I am aware of the cweiske project and looked at it (and a whole lot of other sql related projects available on Packagist) before I started building this project, but it did not quite do what I wanted it to do, which is why I made this tool (around the same amazing library from the phpmyadmin project as the cweiske project no less). Now I mostly made this for my own usage, so I'm not really willing to build features beyond what is needed for my own usage, but I would be willing to accept pull requests for additional features if someone else wanted to put in the effort of building more functionality.

If someone wanted to do this, I would probably want there to be a refactoring of how we get the parameters into the runner. At the moment there is only one parameter and we just look for it in the `src/SqlLint.php` file, but if there are to be more parameters there should be a help command too, and probably a configuration file option so parameters don't have to be passed in via command line parameters.

Whilst this is certainly doable (including the path option you're looking for, this would mostly require getting the path and passing it through to the runner where the path is currently hardcoded), it's not really a priority for me at this point.

**Comment by madaxel** [comment]
Hi @FO-nTTaX ,
thanks for your feedback. Since I like the JUnit output format for GitLab integration I would like to get this working. Looking into the code the easiest way looks like porting your JUnit Report to the Cweiske project. 
Can I take parts of your code? I would create an MR there and let you know about it.

**Comment by FO-nTTaX** [comment]
The code is licensed under GPL-2.0 or later, so as long as you follow that license you can use the code. I'm not a lawyer, I don't know how the legal compatibility between the two projects looks like.
